# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshotter/utils/models/proto/snapshot_submission/submission.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCsnapshotter/utils/models/proto/snapshot_submission/submission.proto\x12\nsubmission\"T\n\x07Request\x12\x10\n\x08\x64\x65\x61\x64line\x18\x01 \x01(\x04\x12\x13\n\x0bsnapshotCid\x18\x02 \x01(\t\x12\x0f\n\x07\x65pochId\x18\x03 \x01(\x04\x12\x11\n\tprojectId\x18\x04 \x01(\t\"]\n\x12SnapshotSubmission\x12$\n\x07request\x18\x01 \x01(\x0b\x32\x13.submission.Request\x12\x11\n\tsignature\x18\x02 \x01(\t\x12\x0e\n\x06header\x18\x03 \x01(\t\"%\n\x12SubmissionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2`\n\nSubmission\x12R\n\x0eSubmitSnapshot\x12\x1e.submission.SnapshotSubmission\x1a\x1e.submission.SubmissionResponse(\x01\x42\x34Z2github.com/PowerLoom/proto-snapshot-collector/pkgsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snapshotter.utils.models.proto.snapshot_submission.submission_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/PowerLoom/proto-snapshot-collector/pkgs'
  _globals['_REQUEST']._serialized_start=83
  _globals['_REQUEST']._serialized_end=167
  _globals['_SNAPSHOTSUBMISSION']._serialized_start=169
  _globals['_SNAPSHOTSUBMISSION']._serialized_end=262
  _globals['_SUBMISSIONRESPONSE']._serialized_start=264
  _globals['_SUBMISSIONRESPONSE']._serialized_end=301
  _globals['_SUBMISSION']._serialized_start=303
  _globals['_SUBMISSION']._serialized_end=399
# @@protoc_insertion_point(module_scope)
