@startuml

AggregateProcessor -> ProtocolStateContractorRedis : Get project first epoch

alt calculating aggregate for the first time
    AggregateProcessor -> ProtocolStateContractorRedis : Get required base snapshots and calculate aggregate from scratch
else calculating aggregate other than the first time
    AggregateProcessor -> ProtocolStateContractorRedis: Get last Finalized Aggregate Snapshot
    ProtocolStateContractorRedis -> AggregateProcessor: LastAggregateSnapshot
    alt if last Finalized Aggregate Snapshot is not found
        AggregateProcessor -> ProtocolStateContractorRedis : Get required base snapshots and calculate aggregate from scratch
    else last Finalized Aggregate Snapshot is found
        AggregateProcessor -> ProtocolStateContractorRedis : Get required (remaining) base snapshots
        LastAggregateSnapshot -> LastAggregateSnapshot: Calculate aggregate from last Finalized Aggregate Snapshot by adding all missing base snapshots
    end

    AggregateProcessor -> ProtocolStateContractorRedis: Fetch tail snapshots for corresponding added snapshots and mark for removal from Aggregate Snapshot

    LastAggregateSnapshot -> LastAggregateSnapshot: Remove marked tail snapshots from Aggregate Snapshot

    LastAggregateSnapshot -> AggregateProcessor: Finalized Aggregate Snapshot
end
@enduml
